accounts/urls.py
from django.urls import path

from accounts.views import UserAPIView

app_name = "accounts"

urlpatterns = [
    path("users/", UserAPIView.as_view(), name="users"),
]

rewardme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("transactions.urls", namespace="transactions")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

transactions/urls.py
from django.urls import path

from transactions.views import index, transact

app_name = "transactions"

urlpatterns = [
    path("", index, name="index"),
    path("transact/", transact, name="transact"),
]

accounts/models.py
from datetime import timedelta

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager, AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.text import gettext_lazy as _

from core.models import TimeStampedModel
from core.utils import random_number_token
from core.validators import MobileNumberValidator


class User(TimeStampedModel, AbstractBaseUser, PermissionsMixin):
    # username will be user's mobile number
    username = models.CharField(
        verbose_name=_("Mobile Number"),
        max_length=10,
        unique=True,
    )
    email = models.EmailField(max_length=255, null=True, blank=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"

    objects = UserManager()

    def __str__(self):
        return str(self.username)

    def save(self, *args, **kwargs):
        validator = MobileNumberValidator()
        validator(self.username)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")
        ordering = ("-created_at",)
        indexes = [models.Index(fields=["username"])]


class OTPValidation(TimeStampedModel):
    # if otp is validated, set this to null
    otp = models.CharField(verbose_name=_("OTP"), max_length=6, null=True, blank=True)
    valid_until = models.DateTimeField(
        default=timezone.now,
        help_text="The timestamp of the moment of expiry of the saved token.",
    )
    destination = models.CharField(
        verbose_name=_("OTP Generated For"),
        max_length=10,
        unique=True,
    )
    is_validated = models.BooleanField(default=False)
    validate_attempt = models.IntegerField(verbose_name=_("Attempted Validation"), default=3)
    # if validate attempt reached 0 then, stop user to create new otp for 24 hours
    otp_reactive_at = models.DateTimeField(verbose_name=_("OTP Reactive At"), null=True, blank=True)
    extra_data = models.JSONField(blank=True, null=True)

    def __str__(self):
        return self.destination

    class Meta:
        ordering = ["-created_at"]
        verbose_name = _("OTP Validation")
        verbose_name_plural = _("OTP Validations")
        indexes = [models.Index(fields=["destination"])]

    def generate_otp(self, length=6, valid_secs=600) -> None:
        """
        Generates a token of the specified length, then sets it on the model
        and sets the expiration of the token on the model.
        Pass 'commit=False' to avoid calling self.save().
        :param int length: Number of decimal digits in the generated token.
        :param int valid_secs: Amount of seconds the token should be valid.
        """
        otp = random_number_token(length)
        self.otp = otp
        self.valid_until = timezone.now() + timedelta(seconds=valid_secs)
        self.save(update_fields=["otp", "valid_until"])

        self._send_otp(f"Here's your OTP, {otp}", "1234567890", [self.destination])

    def verify_otp(self, otp):
        """
        Verifies a token by content and expiry.
        On success, the token is cleared and the device saved.
        :param str otp: The OTP token provided by the user.
        :rtype: bool
        """
        now_ = timezone.now()

        if self.otp is None or otp != self.otp or now_ >= self.valid_until:
            raise ValidationError("Invalid OTP Provided. Please try again.")

        self.token = None
        self.valid_until = now_
        self.save(update_fields=["otp", "valid_until"])
        return True

    def _send_otp(self, message, sms_from, sms_to: list[str]):
        from sms import send_sms

        send_sms(message, sms_from, sms_to)

templates/_base.html
{% load compress static django_htmx %}

<!DOCTYPE html>
<html lang="en-US" class="bg-white subpixel-antialiased">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}{% endblock %} &ndash; Reward Me</title>

    {% compress css %}
        <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}
</head>
<body class="min-h-screen flex flex-col">
{% block navigation %}
{% endblock navigation %}
<main class="{% block main_css_classes %}container mx-auto p-8 grow print:max-w-none{% endblock main_css_classes %}">
    {% if messages %}
        <ul class="flex flex-row justify-center mx-4 -mt-4 mb-4 w-full">
            {% for message in messages %}
                {% block message_block %}
                    <li class="bg-yellow-200 border border-yellow-300 text-blue-900 p-4 mx-2 rounded-lg shadow-sm">{{ message }}</li>
                {% endblock %}
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}{% endblock content %}
</main>
{% block footer %}
{% endblock footer %}
<!-- new -->
{% compress js %}
    <script type="text/javascript" src="{% static 'src/htmx.min.js' %}" defer></script>
{% endcompress %}
<!-- new -->
<script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
</script>

</body>
</html>

templates/fields.html
<div class="md:flex md:items-center {% if not field.errors %}mb-6{% endif %}">
    {% if no_label %}
        <div class="w-full">
    {% else %}
        <div class="md:w-1/4 {% if field.field.widget.input_type == "checkbox" %}self-start{% endif %}">
            <label class="block text-blue-900 font-extralight md:text-right mb-1 md:mb-0 pr-4"
                   for="{{ field.id_for_label }}">
                {{ field.label|title }}
            </label>
        </div>
        <div class="md:w-3/4">
    {% endif %}
    {% if field.widget_type == "textarea" %}
        <textarea
                class="bg-white appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:border-blue-500"
                rows="4"
                id="{{ field.id_for_label }}"
                name="{{ field.html_name }}"
                {% if autofocus %}autofocus{% endif %}
                {% if hx_get %}hx-get="{{ hx_get }}"{% endif %}
                {% if hx_trigger %}hx-trigger="{{ hx_trigger }}"{% endif %}
        >{% if field.value %}{{ field.value|safe|escape }}{% endif %}</textarea>
    {% elif field.field.widget.input_type == "checkbox" %}
        <input class="ml-1" type="checkbox" id="{{ field.id_for_label }}" name="{{ field.html_name }}"
               {% if field.value %}checked{% endif %}>
        {% if field.help_text %}
            <div class="ml-1 mt-2 text-sm text-gray-600 font-extralight">{{ field.help_text }}</div>
        {% endif %}
    {% elif field.field.widget.input_type == "select" %}
        <select required
                class="border-2 border-gray-200 rounded w-full py-2 px-4 focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                id="{{ field.id_for_label }}"
                type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}">
            {% for choice in field.field.choices %}
                {% if forloop.first %}
                    <option class="font-extralight" value="" disabled selected>{{ field.label|title }}...</option>
                {% else %}
                    <option class="dropdown-item" value="{{ choice.0 }}"
                            {% if field.value %}
                                {% if choice.0 == field.value %}
                            selected
                                {% else %}
                            disabled
                                {% endif %}
                            {% endif %}
                    >{{ choice.1 }}

                    </option>
                {% endif %}
            {% endfor %}
            ></select>

    {% else %}
        <input class="bg-white appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none
        {% if field.errors %}border-red-500 focus:border-red-500{% else %}focus:border-blue-500{% endif %}"
               id="{{ field.id_for_label }}"
               type="{{ field.field.widget.input_type }}"
               name="{{ field.html_name }}"
                {% if field.value or field.value == 0 %}
                    {# This is basically a hack to determine the field type. #}
                    {% if field.field.widget.template_name == 'django/forms/widgets/date.html' %}
               value="{{ field.value|date:"n/j/Y"|default:field.value }}"
                    {% else %}
               value="{{ field.value }}"
                    {% endif %}
                readonly
                {% endif %}
               {% if placeholder %}placeholder="{{ placeholder }}"{% endif %}
               {% if autofocus %}autofocus{% endif %}
                {#                {% include "django/forms/widgets/attrs.html" %}#}
               {% if field.field.required and not dont_require %}required{% endif %}
        >
    {% endif %}
    </div>
    </div>
    {% if field.errors %}
        <div class="md:flex md:items-center mt-2 mb-6">
            <div class="md:w-1/4"></div>
            <div class="md:w-3/4">
                {% for error_message in field.errors %}
                    <p class="text-red-500 text-xs italic">{{ error_message }}</p>
                {% endfor %}
            </div>
        </div>
    {% endif %}

templates/index.html
{% extends "_base.html" %}
{% load static %}

{% block head_title %}Home{% endblock %}

{% block content %}
    <div class="w-full max-w-xs mx-auto">
        <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 border border-blue-300"
              method="POST">
            {% csrf_token %}
            <h1 class="font-bold text-xl mb-2 text-center">Reward Me!</h1>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="id_login">
                    Mobile Number
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:ring"
                       type="tel"
                       name="username"
                       id="id_login"
                       pattern="[6789][0-9]{9}"
                       maxlength="10"
                       type="text"
                       placeholder="Mobile Number" required autofocus
                       oninvalid="this.setCustomValidity('Please enter valid phone number')"
                       onchange="try{setCustomValidity('')}catch(e){}"
                        {% if mobile %}
                       value="{{ mobile }}"
                        {% endif %}
                >
                <br><br>
                {% include "specific_field.html" with field=form.product_type %}
                {% include "specific_field.html" with field=form.invoice_amount %}
            </div>
            <label class="text-gray-700 text-sm font-bold mb-2" for="redeem_points">
                <input
                        class="ml-3"
                        type="checkbox"
                        id="redeem_points"
                        name="redeem_points"
                        value="redeem_points"
                        {% if redeem_points %}
                        checked
                        {% endif %}
                >
                Redeem Points
            </label>
            <br><br>

        {% if otp_enabled %}
            {% if submit_otp %}
                <div class="mb-6">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="id_otp">
                        OTP
                    </label>
                    <label for="id_otp"></label>
                    <input
                            class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:ring"
                            type="text" name="otp" minlength="6" maxlength="6" id="id_otp" placeholder="OTP" required
                            oninvalid="this.setCustomValidity('Please enter valid OTP')"
                            onchange="try{setCustomValidity('')}catch(e){}"
                    >
                </div>
                {% if form.errors %}
                    {% for error in form.non_field_errors %}
                        <p class="text-red-500 text-xs italic mt-8">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            {% endif %}
        {% endif %}

            <div class="flex justify-center items-center">
                <button class="bg-blue-700 hover:bg-blue-500 text-white font-bold py-2 px-4 mt-3 rounded focus:outline-none focus:ring"
                        type="submit">
                    {% if submit_otp and otp_enabled %}
                        Submit OTP
                    {% else %}
                        Submit
                    {% endif %}
                </button>
            </div>
        </form>
    </div>
{% endblock %}

templates/invalid_page.html
<div class="max-w-xl mx-auto">
    <h1 class="font-extralight text-2xl text-blue-900 mb-8">
        Oops
    </h1>

    <p class="font-extralight text-base text-gray-800 mb-2">
        Something went wrong. I'm sorry.
        Please contact support and I will look into it.
    </p>
</div>

templates/specific_field.html
<div class="mb-4">
    <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
        {{ field.label|title }}
    </label>
    {% if field.field.widget.input_type == "select" %}
        <select required
                class="border-2 border-gray-200 rounded w-full py-2 px-4 focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                id="{{ field.id_for_label }}"
                type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}">
            {% for choice in field.field.choices %}
                {% if forloop.first %}
                    <option class="font-extralight" value="" disabled selected>{{ field.label|title }}...</option>
                {% else %}
                    <option class="dropdown-item" value="{{ choice.0 }}"
                            {% if field.value %}
                                {% if choice.0 == field.value %}
                            selected
                                {% else %}
                            disabled
                                {% endif %}
                            {% endif %}
                    >{{ choice.1 }}

                    </option>
                {% endif %}
            {% endfor %}
            >
        </select>

    {% else %}
        <input required
               class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:ring"
               id="{{ field.id_for_label }}"
               type="{{ field.field.widget.input_type }}"
               name="{{ field.html_name }}"
               {% if placeholder %}placeholder="{{ placeholder }}"{% endif %}
                {% if field.value %}
               value="{{ field.value }}"
               readonly
                {% endif %}
        >
    {% endif %}
</div>

templates/success.html
{% extends "_base.html" %}

{% block head_title %}Success{% endblock %}

{% block content %}
    <div class="max-w-xl mx-auto">
        <h1 class="font-extralight text-2xl text-blue-900 mb-8">
            Success
        </h1>

        <p class="font-extralight text-base text-gray-800 mb-2">
            Transaction Created Successfully. <b>Current Points Balance: {{ points }}</b>
        </p>
        <br><br>
        <a href="{% url "transactions:index" %}" class="font-extralight text-base text-blue-900 mb-2">
            Back to Login
        </a>
    </div>
{% endblock content %}

templates/todo.html
{% for todo in todos %}
    <tr
            class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
        <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
            {{ todo.id }}
        </td>
        <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
            {{ todo.title }}
        </td>
        <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
            {% if todo.completed %}
                <span class="rounded bg-green-400 py-1 px-3 text-xs font-bold">Yes</span>
            {% else %}
                <span class="rounded bg-red-400 py-1 px-3 text-xs font-bold">No</span>
            {% endif %}
        </td>
    </tr>
{% endfor %}

templates/transact.html
{% extends "_base.html" %}
{% load static %}

{% block head_title %}Transactions{% endblock %}

{% block content %}
    {% if not 'user_id' in request.session %}
        {% include "invalid_page.html" %}
    {% else %}

        <div class="w-full max-w-xs mx-auto">
            <p class="text-gray-700 text-xl mb-4 text-center">
                Spend more to earn more.</p>


            <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 border border-blue-300"
                  method="POST">
                {% csrf_token %}
                <h1 class="font-bold text-xl mb-2 text-center">Transaction Form</h1>

                {% include "fields.html" with field=form.product_type autofocus=True value=product_type %}
                {% include "fields.html" with field=form.invoice_amount %}
                {% include "fields.html" with field=form.payment_amount %}
                {% include "fields.html" with field=form.payment_type %}
                {% include "fields.html" with field=form.note %}
                <div class="flex items-center justify-center">
                    <button class="bg-blue-700 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring"
                            type="submit">
                        Submit Transaction
                    </button>
                </div>
                {% if form.errors %}
                    {% for error in form.non_field_errors %}
                        <p class="text-red-500 text-xs italic mt-4">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    {% endif %}
{% endblock content %}